name: music_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  curved_navigation_bar: ^1.0.3
  just_audio: ^0.9.35
  audio_video_progress_bar: ^2.0.1
  rxdart: ^0.27.7
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  audio_service: ^0.18.12
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator:
  build_runner:

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/lola/
     - assets/rayhon/
     - assets/yulduz/
     - assets/hamdam/
  fonts:
     - family: textFont
       fonts:
         - asset: assets/fonts/textFont.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
